name: Update Word of the Day

on:
  schedule:
    - cron: "0 6 * * *"  # This runs the action daily at 6 AM UTC
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Word of the Day
        id: wordnik
        run: |
          # Fetch the word of the day from Wordnik API
          WORDNIK_API_KEY="${{ secrets.WORDNIK_API_KEY }}"
          RESPONSE=$(curl -s "https://api.wordnik.com/v4/words.json/wordOfTheDay?api_key=$WORDNIK_API_KEY")
          WORD_OF_DAY=$(echo "$RESPONSE" | jq -r '.word')
          DEFINITION=$(echo "$RESPONSE" | jq -r '.definitions[0].text')

          # Safeguard against missing data
          if [[ -z "$WORD_OF_DAY" || -z "$DEFINITION" ]]; then
            echo "Error: Missing word or definition"
            exit 1
          fi

          # Update the README.md with the Word of the Day
          sed -i "s/> \[!info\] \*\*.*\*\*: .*/> [!info] **$WORD_OF_DAY**: $DEFINITION\n> *Word of the Day*/" README.md


      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update Word of the Day"
          git push https://x-access-token:${{ secrets.GH_SECRET }}@github.com/ethanknights/ethanknights.git HEAD:main

