name: Update Word of the Day

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Word of the Day
        id: fetch_word
        run: |
          WORDNIK_API_KEY="${{ secrets.WORDNIK_API_KEY }}"
          RESPONSE=$(curl -s "https://api.wordnik.com/v4/words.json/wordOfTheDay?api_key=$WORDNIK_API_KEY")
          WORD_OF_DAY=$(echo "$RESPONSE" | jq -r '.word')
          DEFINITION=$(echo "$RESPONSE" | jq -r '.definitions[0].text')

          # Validate fetched data
          if [[ -z "$WORD_OF_DAY" || -z "$DEFINITION" ]]; then
            echo "Error: Missing word or definition from Wordnik API"
            exit 1
          fi

          # Log fetched data for debugging
          echo "Fetched Word of the Day: $WORD_OF_DAY"
          echo "Fetched Definition: $DEFINITION"

          # Update the Word of the Day section in README.md
          sed -i "s|# Word of the Day.*|# Word of the Day\n\n**$WORD_OF_DAY**: $DEFINITION\n\n---|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update Word of the Day"
          git push https://x-access-token:${{ secrets.GH_SECRET }}@github.com/ethanknights/ethanknights.git HEAD:main
